name: Next JS CI

on: 
  push:
    branches:
      - develop
      - 'feature/*'
      - 'ui/*'
      - 'hotfix/*'
  pull_request:
    branches:
      -develop
      -main
  
jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
      
      - name: Run Jest Test
        run: npm run test --coverage --passWithNoTests

  # e2e:
  #   name: Run End-to-End Tests
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
      
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with: 
  #         node-version: 18
  #         cache: 'npm'

  #     - name: Install Dependencies
  #       run: npm ci
      
  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps

  #     - name: Run Next.JS in Background
  #       run: npm run dev &
      
  #     - name: Wait for Next.js to be Ready
  #       run: npx wait-on http://localhost:3000
      
  #     - name: Run Playwright Tests
  #       run: npm run test:e2e
  
  build:
    name: Build Next.JS App
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build

  merge_develop:
    name: Merge Develop Into Main Branch
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Config Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Fetch Latest Changes
        run: git fetch origin

      - name: Merge Develop into Main
        run: |
          git checkout main
          git merge --ff-only develop
          git push origin main